/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_layout copy`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart1` | `/cart1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home1` | `/home1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedido` | `/pedido`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedido1` | `/pedido1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat/chatStyles` | `/chat/chatStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/login.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/register.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/welcome.styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_layout copy`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart1` | `/cart1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home1` | `/home1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pedido` | `/pedido`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pedido1` | `/pedido1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat/chatStyles` | `/chat/chatStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/login.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/register.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/welcome.styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/chat${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_layout copy${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart1${`?${string}` | `#${string}` | ''}` | `/cart1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home1${`?${string}` | `#${string}` | ''}` | `/home1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pedido${`?${string}` | `#${string}` | ''}` | `/pedido${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pedido1${`?${string}` | `#${string}` | ''}` | `/pedido1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat/chatStyles${`?${string}` | `#${string}` | ''}` | `/chat/chatStyles${`?${string}` | `#${string}` | ''}` | `/styles/login.styles${`?${string}` | `#${string}` | ''}` | `/styles/register.styles${`?${string}` | `#${string}` | ''}` | `/styles/welcome.styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_layout copy`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart1` | `/cart1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home1` | `/home1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedido` | `/pedido`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedido1` | `/pedido1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat/chatStyles` | `/chat/chatStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/login.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/register.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/welcome.styles`; params?: Router.UnknownInputParams; };
    }
  }
}
